### ISSUE TITLE
Is it possible to have the song name for comparison?

### ISSUE THREAD

**Issue by gabriellst** [orzanai/Moodify#1]
Hey! Congrats for the awesome project, I was wondering how i could query the actual song for interactive purposes.

Cheers

**Comment by gabriellst** [comment]
I found the corresponding URI in Kaggle, sorry for the incovenience!

**Comment by orzanai** [comment]
Hey Gabriel, thank you for your interest, and sorry for the late answer. I'm happy to hear you found URI included dataset; if you need further information, please don't hesitate to contact me!

Cheers
